### ISSUE TITLE
Suddenly exception in MS Edge: "Unable to get property 'handleEvent' of undefined or null reference"

### ISSUE THREAD

**Issue by Herst** [Bernardo-Castilho/dragdroptouch#10]
It used to work in Microsoft Edge now I'm getting _**"SCRIPT5007: Unable to get property 'handleEvent' of undefined or null reference"**_ in [DragDropTouch.js (143,13)](https://github.com/Bernardo-Castilho/dragdroptouch/blob/master/DragDropTouch.js#L143):
```js
document.addEventListener('test', null, {
    get passive() {
        supportsPassive = true;
        return true;
    }
});
```
This is Edge 40.15063.0 (EdgeHTML 15.15063). Looks like a real browser bug as `handleEvent` is mentioned nowhere in the code and from what read from other people seeing this problem in other libraries. At a quick glance I also couldn't find any obvious workarounds.

**Comment by Herst** [comment]
Went to `about:flags`, clicked the "Reset …" button there, restarted Edge and everything worked again, but at some point the issue came back so I guess that this did not fix it. Seems like the issue is quite elusive.

**Comment by Bernardo-Castilho** [comment]
Thanks for pointing this out.

I think I fixed it by replacing the null with an empty string:

    //document.addEventListener('test', null, {
    document.addEventListener('test', '', {

I was able to see the error before, now it seems to be gone.

**Comment by Herst** [comment]
Seems to have fixed the issue for me as well and also makes sense that replacing `null` would fix it.

**Comment by Bernardo-Castilho** [comment]
Great, thanks for the feedback!
