### ISSUE TITLE
"The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

### ISSUE THREAD

**Issue by Herst** [Bernardo-Castilho/dragdroptouch#11]
From <https://github.com/Bernardo-Castilho/dragdroptouch/blob/master/LICENSE>

> The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

Would that also apply to the minimized version?

**Comment by Bernardo-Castilho** [comment]
Please see this link, I found it useful: http://blog.gskinner.com/archives/2013/01/open-source-licenses-and-js.html

The main idea is when you minify/bundle the code, you will add a comment containing the licensing information for all libraries in the bundled/minified code. That seems like a simple and safe idea.

That's the general case. In the particular case of this DragDropTouch library I promise I won't ever sue anyone even if you forget to include the licensing info ;-)
