### ISSUE TITLE
Support for FlexGrid Range Selection using Touch Gestures

### ISSUE THREAD

**Issue by CalvinDale** [Bernardo-Castilho/dragdroptouch#14]
It would be nice if the user could touch-and-drag to select a range of cells or rows in the FlexGrid. But this gesture doesn't work for your demo on my Windows 10 all-in-one touchscreen machine using either Chrome or Edge. Also it would be nice to support disjoint row-selections using touch gestures for the ListBox selection mode.

**Comment by Bernardo-Castilho** [comment]
Hello Calvin

>>>>>>>>>>>>>
It would be nice if the user could touch-and-drag to select a range of cells or rows in the FlexGrid. But this gesture doesn't work for your demo on my Windows 10 all-in-one touchscreen machine using either Chrome or Edge.
>>>>>>>>>>>>>

I agree, but we would have to add some sort of selection handles (visual or not). Touching and dragging the handles would change the selection, while touching and dragging regular content would scroll the grid content.

This is an interesting area for future research.

>>>>>>>>>>>>>
Also it would be nice to support disjoint row-selections using touch gestures for the ListBox selection mode.
>>>>>>>>>>>>>

Yes, right now that requires a keyboard (ctrl key). Again, we need to do a little research.




Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
