### ISSUE TITLE
Does not work on windows-based touchscreen

### ISSUE THREAD

**Issue by simon-aschemeier** [Bernardo-Castilho/dragdroptouch#46]
Hi,

unfortunately your awesome polyfill does not work on windows touchscreens. I seem to remember that it worked in the past, but at the moment (Win 10 21H1) not. 

In firefox browser, a preceding double-tap on the draggable element makes the dragging work, in chrome / edge this trick doesn't do anything. 

Any idea how this can be fixed?

**Comment by simon-aschemeier** [comment]
Nice, you already fixed this issue but you forget to update your own example :-)

**Comment by Bernardo-Castilho** [comment]
Thanks for the heads-up!

Should be OK now.
