### ISSUE TITLE
Image is not draggable on Canvas. 

### ISSUE THREAD

**Issue by Saqib92** [Bernardo-Castilho/dragdroptouch#53]
I am using Fabric.js for my Image Editing App based on Angular 15.

My html `draggable="true"` is not working on mobile Screens. I found your polyfill. after adding it i am able to drag my images but its not going onto Canvas. Dragging stops when my touch reaches to canvas element. apart from canvas element i can drag my image anywhere.

**Comment by Saqib92** [comment]
> Hello! If it works with mouse dragging, then is should work with touch dragging as well. But it's hard to tell what might be happening without seeing a sample and being able to trace/debug the event handlers. If you could send me a sample, I'd be happy to take a look at it. Thanks.

Please have a Look at this stackblitz example. 

[Mobile/ Touch Screen Dragging](https://stackblitz.com/edit/angular-ivy-krhrsx?file=src%2Fapp%2Fapp.component.html)

**Comment by Saqib92** [comment]
any update?

**Comment by Bernardo-Castilho** [comment]
Thanks for sending the sample.

I forked your project to be able to test it:

https://stackblitz.com/edit/angular-ivy-omjvf3?file=src/app/app.component.ts

Tracing through the code, I can see that the DragDropTouch object is trying to dispatch some events but those are not working. It looks to me like zone.js is doing something that prevents the events from being dispatched correctly.

If you look at the code in my blitz (index.html file), you will find two comments that start with "// ***".

The first is the place where we dispatch a mousemove event (to match a touchmove). This returns true, as if the event handler had been called and canceled the event.

The second is the place where we dispatch the drop event (to match a touchend). If you trace through this, you will see that the dispatchEvent method got patched to globalZoneAwareCallback, which for some reason doesn't seem to work in this situation. The actual event handler never gets called, so the drop never happens.

I know zone.js is a complex piece of code, and it might be possible to configure it so it doesn't interfere with the dispatchEvent method. But unfortunately I am not very familiar with it, and didn't have time to dig into this any further.

Sorry I couldn't help more...

**Comment by Saqib92** [comment]
I Managed to make it work, Actually it was Fabric Canvas with z-index which was preventing dragging on to canvas.
I added `z-index: -1` to canvas on `dragstart` and `z-index: 0` on `drop`. it worked as expected. 
But i have found the difference in events, 
With mouse i get Event type as `DropEvent`.
with Touch i get Event type as `Event` only. 
with different inner objects / options.
Main different was in `DropEvent` i received `layerX` and `layerY` exact position of pointer. but in Touch Screen this layer object is missing.

**Comment by Bernardo-Castilho** [comment]
Excellent, congratulations on finding the root of the problem!

You should be able to get the pointer position using the event's clientX and clientY properties.

**Comment by Saqib92** [comment]
> Excellent, congratulations on finding the root of the problem!
> 
> You should be able to get the pointer position using the event's clientX and clientY properties.

Yes I figured that out. Thank you for this Great Help and Library. Really Appreciate.
