### ISSUE TITLE
dblclick event triggered twice on touch screens

### ISSUE THREAD

**Issue by Jimmys20** [Bernardo-Castilho/dragdroptouch#57]
Using this library makes the dblclick event to be triggered two times on touch screens. Here is a demo https://jsfiddle.net/ouLzd13f/.

The library states that it will:

> Raise the dblclick event when there's a new touchstart right after a click

But newer browsers handle the dblclick event natively so this makes the event dispatch twice.

**Comment by Bernardo-Castilho** [comment]
You are right, thanks so much for noticing and reporting this issue.

I will update the library in the next couple of minutes.

Thanks again!
