### ISSUE TITLE
Internal selections is not working

### ISSUE THREAD

**Issue by aksmand3** [Bernardo-Castilho/dragdroptouch#58]
Hello! I'm just a newer in js, your code very helpful.
In my case, the internal selections stop working, but drag and drop finally working correctly.
Where is can be an issue?
[image deleted]

**Comment by Bernardo-Castilho** [comment]
Hard to say without more info. Do you have a sample that I can look at?

**Comment by aksmand3** [comment]
There is. I'm sorry if this trouble is not in your code, this my first test project.
[app_test.zip](https://github.com/Bernardo-Castilho/dragdroptouch/files/12430219/app_test.zip)


> Hard to say without more info. Do you have a sample that I can look at?

**Comment by Bernardo-Castilho** [comment]
Thanks for sending the sample.
I can see a menu showing several images, and I can select any item.
I don't see anything draggable, nor any draggable attributes on the page...
Can you describe the problem?

**Comment by aksmand3** [comment]
Click on this button
![image](https://github.com/Bernardo-Castilho/dragdroptouch/assets/108067100/89596dbf-9116-45f4-b3b5-cd3e034e4365)
Choose this
![image](https://github.com/Bernardo-Castilho/dragdroptouch/assets/108067100/2b0560bd-73d6-4c4c-9b7f-603b5ac5bca0)
Then add some by clicking on plus button
![image](https://github.com/Bernardo-Castilho/dragdroptouch/assets/108067100/70e338fa-8104-43b5-ba08-9cbf29ab3649)
This elements have a draggable attributes

**Comment by Bernardo-Castilho** [comment]
It looks to me like the select elements stop working because the **DragDropTouch** class is handling the **touchstart** event and taking over.

I think this workaround fixes the problem:

```
// scriptes.js, line 1
document.addEventListener('DOMContentLoaded', function () {

    // ** BJC changes start
    // don't drag by select/input/textarea elements
    DragDropTouch.DragDropTouch.prototype._closestDraggable = function (e) {

        if (e instanceof HTMLSelectElement ||
            e instanceof HTMLInputElement ||
            e instanceof HTMLTextAreaElement) {
            //console.log("stop looking on input element")
            return null;
        }

        for (; e; e = e.parentElement) {
            if (e.hasAttribute('draggable') && e.draggable) {
                return e;
            }
        }
        return null;
    };
    // ** BJC changes end

```

Perhaps this should be in the **DragDropTouch** class, but I am not 100% sure.

In the meantime, I hope the workaround works for you.

PS: I think the DragDropTouch,js file in the zip you sent me is out of date, please make sure you get the latest from github.

**Comment by aksmand3** [comment]
It's works! Thank you so much!!!

**Comment by Bernardo-Castilho** [comment]
That's great news, thank you so much for the feedback!

I will add this to the library so in the future it will work "out of the box".

**Comment by Bernardo-Castilho** [comment]
I just made a commit with a beter fix.
Now you can use your inputs as usual, and you can drag elements by dragging the inputs as well.
Thanks again for bringing up this issue!

**Comment by Bernardo-Castilho** [comment]
Selections should be ok now
