### ISSUE TITLE
Enabling the polyfill only when draggable attribute is set

### ISSUE THREAD

**Issue by rbozan** [Bernardo-Castilho/dragdroptouch#64]
Hi, thanks for the PKG.

The line here seems to have changed to make default draggable attributes also draggable on mobile:

https://github.com/Bernardo-Castilho/dragdroptouch/blob/415fcf577d39bfac042d9215a02660d5c1df2f10/DragDropTouch.js#L453

However I'd suggest a toggle to change this behavior back to the old one, because making these elements draggable by default (like a and img) disables scrolling when you start scrolling from those elements, at least on iOS Safari and Android Chrome. The workaround seems to be to set draggable to false on every <a> attribute but that would be a bigger hassle than just re-enabling that line or having that line be toggleable.

**Comment by Bernardo-Castilho** [comment]
The idea behid this change is to make the library more compatible with mouse-based drag/drop.

Link and image elements are draggable by default (with the mouse), so it makes sense for them to be draggable by touch as well.

Of cousrse you can prevent that by setting the draggable attribute to false.
