### ISSUE TITLE
Playwright install in postinstall

### ISSUE THREAD

**Issue by dbaynard** [Bernardo-Castilho/dragdroptouch#72]
https://github.com/Bernardo-Castilho/dragdroptouch/blob/1eea230f0f8ceacfb457b1b8893e9c3938649019/package.json#L13

This appears to have slipped through code review. Surely this is not the intended behaviour?

(It tries to install a browser when installing the package; in my case it failed.)

**Comment by Pomax** [comment]
Yeah that's a bit overbearing, let's fix that...
