### ISSUE TITLE
Uncaught TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.

### ISSUE THREAD

**Issue by DJD10** [Bernardo-Castilho/dragdroptouch#9]
Hey,

I've been trying to implement dragdroptouch in a small project. It's a game of Mastermind, written in html and vanilla Javascript.

It works as expected on desktop browsers, but only partly on Android (haven't tested iOS).

That is to say, I can drag, but not drop.
When I drop an item, I get the error in the subject line, and can trace it to lines 378 and 250 in DragDropTouch.js

The game/source can be found here: http://world.is/games/mastermind/

Any help would be highly appreciated.

-DJ-

**Comment by Bernardo-Castilho** [comment]
It looks like you are setting the transfer data in the "text" format.

I believe it should be "text/plain" instead.

Please give that a try OK?

PS: I will ammend the polyfill to make it more compatible with the desktop version, and get the "text/plain" content when you request "text" as well.
